name: Cov-Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  check-license:
    name: "Check License"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main
  build:
    name: "BifroMQ Code Coverage Test"
    needs: check-license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install TestSuites
        run: mvn install -pl testsuites -am
      - name: Build with Maven
        run: mvn clean verify -P build-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: jacoco
