name: github-packages-publish

on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

  publish-github-packages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish to GitHub Packages
        run: mvn clean deploy -P github-packages-deploy -pl :base-cluster,:base-env-provider,:base-env-provider-spi,:base-hlc,:base-crdt-store,:base-crdt-service,:base-logger,:base-hookloader,:base-kv-store-balance-spi,:bifromq-plugin-archetype,:bifromq-plugin-context,:bifromq-plugin-main,:bifromq-plugin-auth-provider,:bifromq-plugin-event-collector,:bifromq-plugin-resource-throttler,:bifromq-plugin-sub-broker,:bifromq-plugin-setting-provider -am -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}